// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"belajar-golang-restful-api/app"
	"belajar-golang-restful-api/controller"
	"belajar-golang-restful-api/middleware"
	"belajar-golang-restful-api/repository"
	"belajar-golang-restful-api/service"
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	noteRepository := repository.NewNoteRepository()
	db := app.NewDB()
	validate := validator.New()
	noteService := service.NewNoteService(noteRepository, db, validate)
	noteController := controller.NewNoteController(noteService)
	router := app.NewRouter(noteController)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := app.NewServer(authMiddleware)
	return server
}

// injector.go:

var noteSet = wire.NewSet(repository.NewNoteRepository, wire.Bind(new(repository.NoteRepositoryInterface), new(*repository.NoteRepository)), service.NewNoteService, wire.Bind(new(service.NoteServiceInterface), new(*service.NoteService)), controller.NewNoteController, wire.Bind(new(controller.NoteControllerInterface), new(*controller.NoteController)))
